
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label lblKey;

	private global::Gtk.Button btSaveKey;

	private global::Gtk.Button btDeleteKey;

	private global::Gtk.Button btGetKey;

	private global::Gtk.RadioButton _micRadioButton;

	private global::Gtk.RadioButton _micDictationRadioButton;

	private global::Gtk.RadioButton _micIntentRadioButton;

	private global::Gtk.Label lblLUIS;

	private global::Gtk.RadioButton _dataShortRadioButton;

	private global::Gtk.RadioButton _dataLongRadioButton;

	private global::Gtk.RadioButton _dataShortIntentRadioButton;

	private global::Gtk.Label lblSpeechSource;

	private global::Gtk.Label lblLUIS2;

	private global::Gtk.Button _startButton;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView _logText;

	private global::Gtk.TextView textview1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblKey = new global::Gtk.Label();
		this.lblKey.Name = "lblKey";
		this.fixed1.Add(this.lblKey);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblKey]));
		w1.X = 281;
		w1.Y = 41;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btSaveKey = new global::Gtk.Button();
		this.btSaveKey.CanFocus = true;
		this.btSaveKey.Name = "btSaveKey";
		this.btSaveKey.UseUnderline = true;
		this.btSaveKey.Label = global::Mono.Unix.Catalog.GetString("Save Key");
		this.fixed1.Add(this.btSaveKey);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btSaveKey]));
		w2.X = 882;
		w2.Y = 46;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btDeleteKey = new global::Gtk.Button();
		this.btDeleteKey.CanFocus = true;
		this.btDeleteKey.Name = "btDeleteKey";
		this.btDeleteKey.UseUnderline = true;
		this.btDeleteKey.Label = global::Mono.Unix.Catalog.GetString("Delete Key");
		this.fixed1.Add(this.btDeleteKey);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btDeleteKey]));
		w3.X = 960;
		w3.Y = 45;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btGetKey = new global::Gtk.Button();
		this.btGetKey.CanFocus = true;
		this.btGetKey.Name = "btGetKey";
		this.btGetKey.UseUnderline = true;
		this.btGetKey.Label = global::Mono.Unix.Catalog.GetString("Get Key");
		this.fixed1.Add(this.btGetKey);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btGetKey]));
		w4.X = 1048;
		w4.Y = 49;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this._micRadioButton = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Use Microphone with ShortPhrase mode"));
		this._micRadioButton.CanFocus = true;
		this._micRadioButton.Name = "_micRadioButton";
		this._micRadioButton.DrawIndicator = true;
		this._micRadioButton.UseUnderline = true;
		this._micRadioButton.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.fixed1.Add(this._micRadioButton);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this._micRadioButton]));
		w5.X = 108;
		w5.Y = 127;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this._micDictationRadioButton = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Use Microphone with LongDictation mode"));
		this._micDictationRadioButton.CanFocus = true;
		this._micDictationRadioButton.Name = "_micDictationRadioButton";
		this._micDictationRadioButton.DrawIndicator = true;
		this._micDictationRadioButton.UseUnderline = true;
		this._micDictationRadioButton.Group = this._micRadioButton.Group;
		this.fixed1.Add(this._micDictationRadioButton);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this._micDictationRadioButton]));
		w6.X = 108;
		w6.Y = 176;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this._micIntentRadioButton = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Use Microphone and intent detection"));
		this._micIntentRadioButton.CanFocus = true;
		this._micIntentRadioButton.Name = "_micIntentRadioButton";
		this._micIntentRadioButton.DrawIndicator = true;
		this._micIntentRadioButton.UseUnderline = true;
		this._micIntentRadioButton.Group = this._micRadioButton.Group;
		this.fixed1.Add(this._micIntentRadioButton);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this._micIntentRadioButton]));
		w7.X = 120;
		w7.Y = 216;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblLUIS = new global::Gtk.Label();
		this.lblLUIS.Name = "lblLUIS";
		this.lblLUIS.LabelProp = global::Mono.Unix.Catalog.GetString("(* LUIS registration is needed.)");
		this.fixed1.Add(this.lblLUIS);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblLUIS]));
		w8.X = 191;
		w8.Y = 252;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this._dataShortRadioButton = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Use wav file for ShortPhrase mode"));
		this._dataShortRadioButton.CanFocus = true;
		this._dataShortRadioButton.Name = "_dataShortRadioButton";
		this._dataShortRadioButton.DrawIndicator = true;
		this._dataShortRadioButton.UseUnderline = true;
		this._dataShortRadioButton.Group = this._micRadioButton.Group;
		this.fixed1.Add(this._dataShortRadioButton);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this._dataShortRadioButton]));
		w9.X = 197;
		w9.Y = 288;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this._dataLongRadioButton = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Use wav file for LongDictation mode"));
		this._dataLongRadioButton.CanFocus = true;
		this._dataLongRadioButton.Name = "_dataLongRadioButton";
		this._dataLongRadioButton.DrawIndicator = true;
		this._dataLongRadioButton.UseUnderline = true;
		this._dataLongRadioButton.Group = this._micRadioButton.Group;
		this.fixed1.Add(this._dataLongRadioButton);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this._dataLongRadioButton]));
		w10.X = 207;
		w10.Y = 321;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this._dataShortIntentRadioButton = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Use wav file and intent detection"));
		this._dataShortIntentRadioButton.CanFocus = true;
		this._dataShortIntentRadioButton.Name = "_dataShortIntentRadioButton";
		this._dataShortIntentRadioButton.DrawIndicator = true;
		this._dataShortIntentRadioButton.UseUnderline = true;
		this._dataShortIntentRadioButton.Group = this._micRadioButton.Group;
		this.fixed1.Add(this._dataShortIntentRadioButton);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this._dataShortIntentRadioButton]));
		w11.X = 216;
		w11.Y = 356;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblSpeechSource = new global::Gtk.Label();
		this.lblSpeechSource.Name = "lblSpeechSource";
		this.lblSpeechSource.LabelProp = global::Mono.Unix.Catalog.GetString("Speech Recognition Source:");
		this.fixed1.Add(this.lblSpeechSource);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblSpeechSource]));
		w12.X = 114;
		w12.Y = 95;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblLUIS2 = new global::Gtk.Label();
		this.lblLUIS2.Name = "lblLUIS2";
		this.lblLUIS2.LabelProp = global::Mono.Unix.Catalog.GetString("(* LUIS registration is needed.)");
		this.fixed1.Add(this.lblLUIS2);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblLUIS2]));
		w13.X = 211;
		w13.Y = 395;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this._startButton = new global::Gtk.Button();
		this._startButton.CanFocus = true;
		this._startButton.Name = "_startButton";
		this._startButton.UseUnderline = true;
		this._startButton.Label = global::Mono.Unix.Catalog.GetString("Start _Recognition");
		this.fixed1.Add(this._startButton);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this._startButton]));
		w14.X = 143;
		w14.Y = 470;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this._logText = new global::Gtk.TextView();
		this._logText.CanFocus = true;
		this._logText.Name = "_logText";
		this.GtkScrolledWindow.Add(this._logText);
		this.fixed1.Add(this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
		w16.X = 922;
		w16.Y = 124;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.Buffer.Text = global::Mono.Unix.Catalog.GetString("{Binding ElementName=_mainWindow, Path=SubscriptionKey, Mode=TwoWay}");
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.fixed1.Add(this.textview1);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.textview1]));
		w17.X = 421;
		w17.Y = 55;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1249;
		this.DefaultHeight = 637;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btGetKey.Clicked += new global::System.EventHandler(this.HelpButton_Click);
		this._startButton.Clicked += new global::System.EventHandler(this.StartButton_Click);
	}
}
